//! KV-backed payment storage for BRC-29 payments.

use crate::error::{AuthCloudflareError, Result};
use crate::types::StoredPayment;
use worker::kv::KvStore;

/// Payment storage backed by Cloudflare KV.
///
/// This stores payment records for BRC-29 paid requests.
pub struct KvPaymentStorage {
    kv: KvStore,
    prefix: String,
}

impl KvPaymentStorage {
    /// Creates a new KV payment storage.
    ///
    /// # Arguments
    ///
    /// * `kv` - The Cloudflare KV namespace
    /// * `prefix` - Prefix for all keys (to allow multiple instances)
    pub fn new(kv: KvStore, prefix: &str) -> Self {
        Self {
            kv,
            prefix: prefix.to_string(),
        }
    }

    /// Constructs the KV key for a payment by txid and vout.
    fn payment_key(&self, txid: &str, vout: u32) -> String {
        format!("{}:payment:{}:{}", self.prefix, txid, vout)
    }

    /// Constructs the KV key for the unspent index.
    fn unspent_key(&self, txid: &str, vout: u32) -> String {
        format!("{}:unspent:{}:{}", self.prefix, txid, vout)
    }

    /// Constructs the KV key for derivation prefix tracking.
    fn derivation_key(&self, derivation_prefix: &str) -> String {
        format!("{}:derivation:{}", self.prefix, derivation_prefix)
    }

    /// Gets a payment by txid and vout.
    pub async fn get_payment(&self, txid: &str, vout: u32) -> Result<Option<StoredPayment>> {
        let key = self.payment_key(txid, vout);
        match self.kv.get(&key).json::<StoredPayment>().await {
            Ok(payment) => Ok(payment),
            Err(e) => Err(AuthCloudflareError::KvError(e.to_string())),
        }
    }

    /// Checks if a payment exists (duplicate check).
    pub async fn payment_exists(&self, txid: &str, vout: u32) -> Result<bool> {
        Ok(self.get_payment(txid, vout).await?.is_some())
    }

    /// Stores a payment record.
    pub async fn store_payment(&self, payment: &StoredPayment) -> Result<()> {
        let payment_key = self.payment_key(&payment.txid, payment.vout);
        let json = serde_json::to_string(payment)?;

        self.kv
            .put(&payment_key, &json)
            .map_err(|e| AuthCloudflareError::KvError(e.to_string()))?
            .execute()
            .await
            .map_err(|e| AuthCloudflareError::KvError(e.to_string()))?;

        // Mark as unspent
        if !payment.spent {
            let unspent_key = self.unspent_key(&payment.txid, payment.vout);
            self.kv
                .put(&unspent_key, "1")
                .map_err(|e| AuthCloudflareError::KvError(e.to_string()))?
                .execute()
                .await
                .map_err(|e| AuthCloudflareError::KvError(e.to_string()))?;
        }

        Ok(())
    }

    /// Marks a payment as spent.
    pub async fn mark_spent(&self, txid: &str, vout: u32) -> Result<()> {
        if let Some(mut payment) = self.get_payment(txid, vout).await? {
            payment.spent = true;
            self.store_payment(&payment).await?;

            // Remove from unspent index
            let unspent_key = self.unspent_key(txid, vout);
            let _ = self.kv.delete(&unspent_key).await;
        }
        Ok(())
    }

    /// Stores a derivation prefix as used (for nonce tracking).
    ///
    /// This allows verification that a derivation prefix was generated by this server.
    pub async fn store_derivation_prefix(
        &self,
        derivation_prefix: &str,
        ttl_seconds: u64,
    ) -> Result<()> {
        let key = self.derivation_key(derivation_prefix);
        self.kv
            .put(&key, "1")
            .map_err(|e| AuthCloudflareError::KvError(e.to_string()))?
            .expiration_ttl(ttl_seconds)
            .execute()
            .await
            .map_err(|e| AuthCloudflareError::KvError(e.to_string()))?;
        Ok(())
    }

    /// Checks if a derivation prefix exists and removes it (one-time use).
    pub async fn consume_derivation_prefix(&self, derivation_prefix: &str) -> Result<bool> {
        let key = self.derivation_key(derivation_prefix);
        match self.kv.get(&key).text().await {
            Ok(Some(_)) => {
                let _ = self.kv.delete(&key).await;
                Ok(true)
            }
            Ok(None) => Ok(false),
            Err(e) => Err(AuthCloudflareError::KvError(e.to_string())),
        }
    }

    /// Gets total satoshis received from a specific identity.
    pub async fn get_total_from_identity(&self, identity_key: &str) -> Result<u64> {
        // This is expensive - in production, consider maintaining a counter
        let prefix = format!("{}:payment:", self.prefix);
        let list = self
            .kv
            .list()
            .prefix(prefix)
            .execute()
            .await
            .map_err(|e| AuthCloudflareError::KvError(e.to_string()))?;

        let mut total = 0u64;
        for key in list.keys {
            if let Ok(Some(payment)) = self.kv.get(&key.name).json::<StoredPayment>().await {
                if payment.sender_identity_key == identity_key {
                    total = total.saturating_add(payment.satoshis);
                }
            }
        }

        Ok(total)
    }
}
